language: python
dist: xenial
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- python setup.py test
deploy:
  provider: pypi
  user: "jelleaalbers"
  password:
    secure: Un7Xajh0mIc/gKZ8j6SYO5Dq3zG1rcxiuD77fbJdoDyxZFzSYhBBoEnJGhgKGOIwaZkq1MXvYNZ8bSwVpENYBbASW/sL+UIF2Z+r05teCdF39OZY5ZRqCNkrEDlpGTZC7ZhM3C7u/ZSLp2+G7S/s0xQKVruEcLLIwRuMvAGv7NstinBGQiDHLjx5i8YayVBmgYveeZ32LLxoh2D4Za3vYShrahUfC+pp46lXByGckd7lJZieTF2AllUsPipKvA19Z4Nr24WSbyVzavOB6pw9RwV9staMsDjSVB3RkZaZ6MVbnjQrCwi7b8wAMycjA1WahRf3W7jtCsQiazJBk9gCTLj/3RW9qGqnYmlF+eED/XjYuj1wgZ6S5mBT2/AahWxSQCJaF7ZZetz9JADbnnBds6F3K/94BXSCZIlSJqVNQMfu3qM2M/vIIDZzBDZtwNga9l2mTtJczUYCuCqbntxzZKlYm3vlDWjXvrd95JJ4m4qDSYhWxUP0ocngsJhPEJEB7HWaN/ZFm5gcYI8pNNKaSLHviL8LtbPYXbRsjpzr4SeV2bWWe3UiwJwQCbgPq3K7Abvm+49fQfKy0MywN+0h0IJShGxKiysd9MfV227bkPr7JfOWdKk1z1NxpOrsERnOjh5u2VpJrXnIcyzusb4oQAc2ZXOVa6zj2UQmL34Phgw=
  on:
    tags: true